use_frameworks!

platform :ios, '14.0'

target 'HYLegacyComponents_Example' do
  pod 'HYLegacyComponents', :path => '../'

  target 'HYLegacyComponents_Tests' do
    inherit! :search_paths

    
  end
end
